### ISSUE TITLE
gtags/ref is loosing -rs option

### ISSUE THREAD

**Issue by lepricon** [hewes/unite-gtags#9]
Unite gtags/ref source calls incorrect built_cmd, global gets only "-q" option, but not "-rsq". l:short_option is empty inside unite#libs#gtags#exec_global()
This leads to incorrect output of only one result instead of all references. The last refactor commit introduced this bug.

**Comment by thawk** [comment]
It seens unite#libs#gtags#exec_global() wants to get 'long_option'/'short_option', but there's only 'long'/'short' in the sources/gtags.vim. Maybe sources/gtags.vim needs to be commit too?

**Comment by lepricon** [comment]
You're right! I will try to submit fix.

**Comment by hewes** [comment]
@lepricon, @thawk Oops! Thank you for pointing it out.
I merged  Pull #10
